### ISSUE TITLE
App force closes: No virtual method getPairValue()Ljava/lang/String; in class Landroid/os/Bundle;

### ISSUE THREAD

**Issue by flipsa** [onlymash/LineageOSWeatherProvider#1]
Hey there. 

I'm running LineageOS 16. Your app installs fine, but sadly doesnt work. I tried the LOS cLock widget, but there was a toast message saying sth like "Weather provider currently unreachable". The OWM API field says "verified", but the widget does not show the weather.

The error i see in logcat is this:

```
<<< log_count = 14 >>>
[06-03 00:02:52.291 1172:1172 I/LineageSystemServer]
Attempting to start service org.lineageos.platform.internal.LineageWeatherManagerService

[06-03 00:02:52.293 1172:1172 I/LineageSystemServer]
Starting service org.lineageos.platform.internal.LineageWeatherManagerService

[06-03 00:02:52.293 1172:1172 I/SystemServiceManager]
Starting org.lineageos.platform.internal.LineageWeatherManagerService

[06-03 00:03:10.306 1172:1506 I/ActivityManager]
Start proc 3169:onlymash.lineageos.weather/u0a248 for service onlymash.lineageos.weather/.WeatherMapProviderService

[06-03 00:03:11.261 1172:3346 W/ActivityManager]
Background start not allowed: service Intent { cmp=org.lineageos.lockclock/.weather.WeatherSourceListenerService } to org.lineageos.lockclock/.weather.WeatherSourceListenerService from pid=3660 uid=10075 pkg=org.lineageos.lockclock startFg?=false

[06-03 00:03:33.639 3660:3660 D/WeatherUpdateService]
onCreate

[06-03 00:03:33.689 3169:3169 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: onlymash.lineageos.weather, PID: 3169
java.lang.NoSuchMethodError: No virtual method getPairValue()Ljava/lang/String; in class Landroid/os/Bundle; or its super classes (declaration of 'android.os.Bundle' appears in /system/framework/framework.jar!classes2.dex)
	at lineageos.providers.LineageSettings$NameValueCache.getStringForUser(LineageSettings.java:257)
	at lineageos.providers.LineageSettings$Global.getStringForUser(LineageSettings.java:3299)
	at lineageos.providers.LineageSettings$Global.getIntForUser(LineageSettings.java:3339)
	at lineageos.providers.LineageSettings$Global.getInt(LineageSettings.java:3334)
	at onlymash.lineageos.weather.repository.WeatherRepositoryImpl.getTempUnitFromSettings(WeatherRepositoryImpl.kt:292)
	at onlymash.lineageos.weather.repository.WeatherRepositoryImpl.queryWeather(WeatherRepositoryImpl.kt:82)
	at onlymash.lineageos.weather.WeatherMapProviderService$updateWeather$1$weatherInfo$1.invokeSuspend(WeatherMapProviderService.kt:111)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)

[06-03 00:03:33.722 1172:3349 I/ActivityManager]
Process onlymash.lineageos.weather (pid 3169) has died: vis  IMPF

[06-03 00:03:33.722 1172:1172 D/LineageWeatherManagerService]
Connection with onlymash.lineageos.weather/onlymash.lineageos.weather.WeatherMapProviderService has been closed

[06-03 00:03:33.722 1172:3349 W/ActivityManager]
Scheduling restart of crashed service onlymash.lineageos.weather/.WeatherMapProviderService in 1000ms

[06-03 00:03:34.734 1172:1506 I/ActivityManager]
Start proc 6417:onlymash.lineageos.weather/u0a248 for service onlymash.lineageos.weather/.WeatherMapProviderService

[06-03 00:04:03.709 3660:3660 D/WeatherUpdateService]
onDestroy

```

Let me know if you need more info. 

Cheers! 

Edit: included the logcat here since the pastebin link had expired.

**Comment by flipsa** [comment]
This was fixed in a recent update.
